### ISSUE TITLE
Error when starting game with ArsTheurgia

### ISSUE THREAD

**Issue by angelnc1989** [comofastm/ArsTheurgia#2]
`Exception in thread "main" java.lang.RuntimeException: Failed to read accessWidener file from mod geckolib
	at net.fabricmc.loader.transformer.accesswidener.AccessWidener.loadFromMods(AccessWidener.java:63)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:130)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.RuntimeException: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.loader.transformer.accesswidener.AccessWidener.read(AccessWidener.java:81)
	at net.fabricmc.loader.transformer.accesswidener.AccessWidener.loadFromMods(AccessWidener.java:61)
	... 2 more
`

I get this error when I try to start an instance with ArsTheurgia installed.
Using Fabric 0.10.3+build.211 and ArsTheurgia 1.0.2

**Comment by ymndoseijin** [comment]
We have fixed it, adding GeckoLib as a dependency. 
You can download it here: https://www.curseforge.com/minecraft/mc-mods/geckolib-fabric
And the newest mod version here: https://github.com/comofastm/ArsTheurgia/releases/download/1.0.3/arstheurgia-1.0.3.jar
